version: '3.4'

x-common-variables: &common-variables
 MINIO_ACCESS_KEY: minio
 MINIO_SECRET_KEY: minio123
 MINIO_URL: minio:9000
 MINIO_BUCKET_NAME: hse-api-bucket
 RESTRICTED_MODE: 0

services:
 hse-api-web:
  build:
   context: .
   dockerfile: hseling_api_diachrony_webvectors/Dockerfile
  ports:
   - "5000:80"
  volumes:
   - ./hseling_api_diachrony_webvectors/hseling_api_diachrony_webvectors:/app/hseling_api_diachrony_webvectors
  links:
   - minio
  environment: *common-variables


 minio:
  image: minio/minio:latest
  volumes:
   - data:/data
  ports:
   - "9000:9000"
  command: server /data/minio
  environment: *common-variables





 # Development related
 db:
  env_file: hseling_web_diachrony_webvectors/environment.env
  build:
   context: ./hseling_web_diachrony_webvectors/
   dockerfile: ./docker/db/Dockerfile
   args:
    # These values should be in sync with environment.env
    # for development. If you change them, you'll 
    # need to rebuild the container
    - POSTGRES_DB=templatesitedb
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=somepassword
    - POSTGRES_PORT=5432
    # Remember to keep this consistent
    - django_secret_key=secret_key!

 log:
  env_file: hseling_web_diachrony_webvectors/environment.env
  build:
   context: ./hseling_web_diachrony_webvectors/
   dockerfile: ./docker/log/Dockerfile

 build-deps:
  env_file: hseling_web_diachrony_webvectors/environment.env
  build:
   context: ./hseling_web_diachrony_webvectors/
   dockerfile: ./docker/deps/Dockerfile
  volumes:
   - ./hseling_web_diachrony_webvectors/vendor:/opt/ext_vendor
  command: /opt/copy_deps.sh

 dev-server:
  env_file: hseling_web_diachrony_webvectors/environment.env
  environment:
   - CONSOLE_LOGS=1
  build: 
   context: ./hseling_web_diachrony_webvectors/
   args:
    # Remember to keep this consistent
    - django_secret_key=secret_key!
  command: ./start_dev_server.sh
  ports:
   - "8000:80"
  volumes:
   - ./hseling_web_diachrony_webvectors/src:/opt/code
  depends_on:
   - db
   - log
   - hse-api-web

volumes:
  data:
